"""account add column

Revision ID: 2
Revises: 1
Create Date: 2024-08-05 15:05:25.826430

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2'
down_revision: Union[str, None] = '1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('failed_attempts', sa.SmallInteger(), nullable=False))
    op.add_column('account', sa.Column('block_verification_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'block_verification_time')
    op.drop_column('account', 'failed_attempts')
    # ### end Alembic commands ###
