repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: ruff
      args: ['check .']
      language: system
      types: [python]
  - repo: local
    hooks:
      - id: pytest_account_password_management
        name: pytest_account_password_management
        entry: pytest
        args: ['projects/account_password_management']
        language: system
        stages: [push]
        pass_filenames: false
        always_run: true
