services:
  db:
    image: postgres
    networks:
      - xiao75896453-demo
    ports:
      - "${DOCKER_HOST_DB_PORT}:5432"
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - xiao75896453-demo:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: xiao75896453-${PROJECT_IMAGE_NAME}-db
    restart: always

networks:
  xiao75896453-demo:
    name: xiao75896453-demo-${PROJECT_IMAGE_NAME}

volumes:
  xiao75896453-demo:
    name: xiao75896453-demo-${PROJECT_IMAGE_NAME}-db
