name: ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
    - name: Install dependencies
      run: |
        poetry add ruff
    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
          files_yaml: |
            py:
              - '**.py'
    - name: Linting the code with ruff
      if: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        source .venv/bin/activate
        ruff check ${{ steps.changed-files.outputs.all_changed_files }}
